[tool.ruff]
# Включить больше полезных правил
select = [
    "E",   # Pycodestyle (ошибки)
    "F",   # Pyflakes (ошибки времени выполнения)
    "W",   # Pycodestyle warnings
    "UP",  # Pyupgrade (модернизация кода под новые версии Python)
    "I",   # Isort (сортировка импортов)
    "C90", # McCabe (сложность функций)
]

# Игнорировать правило о длине строки (пусть форматтер этим занимается)
ignore = ["E501"]

# Настройка линтинга
[tool.ruff.lint]
# Другие настройки линтинга можно добавить здесь

# Настройка сложности функций (McCabe)
[tool.ruff.lint.mccabe]
max-complexity = 20

# Настроить форматтер (если используете ruff format)
[tool.ruff.format]
# Использовать двойные кавычки
quote-style = "double"
